name: docker-build

on:
  push:
    branches:
      - '**' # Trigger workflow on push to any branch
  pull_request:
    branches:
      - '**' # Trigger workflow on pull request to any branch
  schedule:
    - cron: '0 * * * *' # Trigger workflow every hour

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout
        with:
          ref: ${{ github.ref }} 

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx (for better compatibility and multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: . # Path to the Dockerfile
          push: true # Push the image after building
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/global-dev-environment-public:latest # Replace 'your-image-name' with your actual image name
          build-args: |
            PYTHON_REQUIREMENTS_URL=${{ secrets.PYTHON_REQUIREMENTS_URL }} 
            PYTHON_SCRIPT_SETUP_URL=${{ secrets.PYTHON_SCRIPT_SETUP_URL }}

      # Optional: Log out of Docker Hub
      - name: Log out of Docker Hub
        run: docker logout
